### ISSUE TITLE
The link to the Library Carpentry OpenRefine lesson is giving me a 404

### ISSUE THREAD

**Issue by dlstrong** [carpentries/scaffolds#5]
Not sure where it should be or how to fix the link, but I'm getting a 404 when I follow that link. (Discovered during this morning's online instructor training.)

**Comment by zkamvar** [comment]
Thank you for letting me know!

GitHub has been changing how it reads links recently and it is now case-sensitive. I fixed the link in #4 so that it should now work: https://github.com/carpentries/scaffolds/blob/master/instructions/workshop-coordination.md#library-carpentry

Feel free to reopen this if it does not work for you.
